### ISSUE TITLE
Parameter not usable twice in query

### ISSUE THREAD

**Issue by alopezalos** [yogeshsd/query2report#7] opened 2018-11-23 09:30 UTC
Might you please verify that a parameter can be used more than once in a query? Attached example bellow.

(select 'a) Total CDS new registered users: '||count(distinct(userid)) as users_info from users_cds where date_trunc('day',data_created) >= {date:date_from} and date_trunc('day',data_created) <= {date:date_to})
UNION
(select 'b) Total CDS active users: '||count(distinct(username)) as users_info from brokerrequest_his where date_trunc('day',receivedat) >= {date:date_from} and date_trunc('day',receivedat) <= {date:date_to});

**Comment by yogeshsd** [comment] 2018-11-27 05:20
The issue is fixed in the latest release

**Closed by yogeshsd** 2018-11-27 05:20 UTC
