### ISSUE TITLE
Adapt inferface options

### ISSUE THREAD

**Issue by alopezalos** [yogeshsd/query2report#4] opened 2018-11-21 17:44 UTC
It would be good to have the possibility to adapt the interface when providing access to the tool to third parties,  for example:
      - remove links to documentation.
      - Include logo.

**Comment by yogeshsd** [comment] 2018-11-22 04:38
The enhancement request is addressed in latest version.

To change the Logo
1. Create a new logo png file of size 150 Pixels ( width ) and 50 Pixels ( Height) 
2. Copy it to {CATALINA_BASE}/q2rapp and rename the file as q2r.png
3. Restart tomcat
4. Refresh the home page and you should see the new logo.


To remove the documentation, video tutorial and feedback links
1. Click on the user icon on the top right
2. Click on "Update Global Config"
3. Set following values to "false" from "true"
      a. show_copyright_links=false
      b. show_video_links=false
      c. show_feedback_links=false
4. Refresh the page.

Thanks
Yogesh

**Closed by yogeshsd** 2018-11-22 04:38 UTC
Labels: enhancement

**Comment by alopezalos** [comment] 2018-11-22 16:50
Hi Yogesh, 
System is not working after update. Attached extractions from logs. 

2018-11-22 16:30:39,923 INFO  localhost-startStop-1id com.lwr.software.reporter.utils.Q2RContextListener.contextInitialized - Creating directories if already created
2018-11-22 16:30:39,925 INFO  localhost-startStop-1id com.lwr.software.reporter.utils.Q2RContextListener.contextInitialized - Creating config directory tree /opt/cds/tomcat/q2rapp/config/
2018-11-22 16:30:39,925 INFO  localhost-startStop-1id com.lwr.software.reporter.utils.Q2RContextListener.contextInitialized - Config directory tree already exists
2018-11-22 16:30:39,925 INFO  localhost-startStop-1id com.lwr.software.reporter.utils.Q2RContextListener.contextInitialized - Creating public report directory tree /opt/cds/tomcat/q2rapp/reports/public/
2018-11-22 16:30:39,926 INFO  localhost-startStop-1id com.lwr.software.reporter.utils.Q2RContextListener.contextInitialized - Public report directory tree already exists
2018-11-22 16:30:39,926 INFO  localhost-startStop-1id com.lwr.software.reporter.utils.Q2RContextListener.contextInitialized - Creating private report directory tree /opt/cds/tomcat/q2rapp/reports/private/
2018-11-22 16:30:39,926 INFO  localhost-startStop-1id com.lwr.software.reporter.utils.Q2RContextListener.contextInitialized - Private report directory tree already exists
2018-11-22 16:30:50,529 INFO  localhost-startStop-1id com.lwr.software.reporter.utils.Q2RContextListener.contextInitialized - Creating directories if already created
2018-11-22 16:30:50,531 INFO  localhost-startStop-1id com.lwr.software.reporter.utils.Q2RContextListener.contextInitialized - Creating config directory tree /opt/cds/tomcat/q2rapp/config/
2018-11-22 16:30:50,531 INFO  localhost-startStop-1id com.lwr.software.reporter.utils.Q2RContextListener.contextInitialized - Config directory tree already exists
2018-11-22 16:30:50,531 INFO  localhost-startStop-1id com.lwr.software.reporter.utils.Q2RContextListener.contextInitialized - Creating public report directory tree /opt/cds/tomcat/q2rapp/reports/public/
2018-11-22 16:30:50,531 INFO  localhost-startStop-1id com.lwr.software.reporter.utils.Q2RContextListener.contextInitialized - Public report directory tree already exists
2018-11-22 16:30:50,531 INFO  localhost-startStop-1id com.lwr.software.reporter.utils.Q2RContextListener.contextInitialized - Creating private report directory tree /opt/cds/tomcat/q2rapp/reports/private/
2018-11-22 16:30:50,531 INFO  localhost-startStop-1id com.lwr.software.reporter.utils.Q2RContextListener.contextInitialized - Private report directory tree already exists


/q2r/rest/reports/personal/public
log4j:ERROR Failed to flush writer,
java.io.IOException: No space left on device
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at org.apache.log4j.helpers.QuietWriter.flush(QuietWriter.java:59)
        at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:324)
        at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
        at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
        at org.apache.log4j.Category.callAppenders(Category.java:206)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.info(Category.java:666)
        at com.lwr.software.reporter.utils.DWHUtility.executeQuery(DWHUtility.java:78)
        at com.lwr.software.reporter.reportmgmt.Element.init(Element.java:303)
        at com.lwr.software.reporter.restservices.ReportManagementService.executeQuery(ReportManagementService.java:189)
        at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourclog4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document root element "log4j:configuration", must match DOCTYPE root "null".
log4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document is invalid: no grammar found.
log4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document root element "log4j:configuration", must match DOCTYPE root "null".
log4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document is invalid: no grammar found.
log4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document root element "log4j:configuration", must match DOCTYPE root "null".
log4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document is invalid: no grammar found.
log4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document root element "log4j:configuration", must match DOCTYPE root "null".
log4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document is invalid: no grammar found.


/q2r/rest/reports/personal/public
log4j:ERROR Failed to flush writer,
java.io.IOException: No space left on device
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at org.apache.log4j.helpers.QuietWriter.flush(QuietWriter.java:59)
        at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:324)
        at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
        at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
        at org.apache.log4j.Category.callAppenders(Category.java:206)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.info(Category.java:666)
        at com.lwr.software.reporter.utils.DWHUtility.executeQuery(DWHUtility.java:78)
        at com.lwr.software.reporter.reportmgmt.Element.init(Element.java:303)
        at com.lwr.software.reporter.restservices.ReportManagementService.executeQuery(ReportManagementService.java:189)
        at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourclog4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document root element "log4j:configuration", must match DOCTYPE root "null".
log4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document is invalid: no grammar found.
log4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document root element "log4j:configuration", must match DOCTYPE root "null".
log4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document is invalid: no grammar found.
log4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document root element "log4j:configuration", must match DOCTYPE root "null".
log4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document is invalid: no grammar found.
log4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document root element "log4j:configuration", must match DOCTYPE root "null".
log4j:WARN Continuable parsing error 2 and column 83
log4j:WARN Document is invalid: no grammar found.




 

    En jueves, 22 de noviembre de 2018 4:38:04 GMT, Yogesh Deshpande <notifications@github.com> escribió:  
 
 
Closed #4.

**Comment by anil1750** [comment] 2019-01-16 09:33
HI Yogesh

I have deployed new instance of q2r.war. I am getting the below errors

Unable to initialize connection manager
java.io.FileNotFoundException: /var/tomcat8/q2rapp/config/connections.json (No such file or directory)
Unable to initialize driver manager
java.io.FileNotFoundException: /var/tomcat8/q2rapp/config/drivers.json (No such file or directory)

Unable to initialize user manager
java.io.FileNotFoundException: /var/tomcat8/q2rapp/config/users.json (No such file or directory)

I did checked /var/tomcat8/q2rapp/config folder, there are no json files. Your support is highly appreciated.

Anil

**Comment by yogeshsd** [comment] 2019-01-17 06:35
Hello Anil,

You typically see this error for the very first time when q2r app is deployed. 

Are you seeing these errors often?

Can you please send me entire q2r.log from CATALINA_BASE/logs folder?

Thanks
Yogesh

**Comment by anil1750** [comment] 2019-01-17 06:42
Hi Yogesh



> Hello Anil,
> 
> You typically see this error for the very first time when q2r app is deployed.
> 
> Are you seeing these errors often?
> 
> Can you please send me entire q2r.log from CATALINA_BASE/logs folder?
> 
> Thanks
> Yogesh

Hi Yogesh

Thanks for the reply, you are right I am getting this for the initial deployment. Please find the logs attached.

Thanks

Anil
[catalinalogs.zip](https://github.com/yogeshsd/query2report/files/2767376/catalinalogs.zip)

**Comment by yogeshsd** [comment] 2019-01-17 09:39
Hello Anil,

I see that you are giving display name but not username. Username is mandatory field and try again by giving appropriate username.

Let me know how it goes.

Thanks
Yogesh

**Comment by anil1750** [comment] 2019-01-17 10:04
> Hello Anil,
> 
> I see that you are giving display name but not username. Username is mandatory field and try again by giving appropriate username.
> 
> Let me know how it goes.
> 
> Thanks
> Yogesh

Hi Yogesh

Logged in as admin user and not getting any options to setup user base or update user giving me Response = "Unable to save user 'Admin'.". Status = 500. Also not allowing me to update the drivers. attached is the log file.

Thank You

Anil
[q2r.log](https://github.com/yogeshsd/query2report/files/2768084/q2r.log)

**Comment by yogeshsd** [comment] 2019-01-17 10:52
Hello Anil,

I believe you are trying to create a user called 'Admin' and getting the error.

1. Can you please send the screenshot when you are trying to creating this user?
2. Username is not null field, but form the logs you sent, i see that username is coming as null and this is the reason why you are getting this error.

Along with screenshot can you also send me the update q2r.log file?

Thanks
Yogesh

**Comment by anil1750** [comment] 2019-01-17 10:58
> Hello Anil,
> 
> I believe you are trying to create a user called 'Admin' and getting the error.
> 
>     1. Can you please send the screenshot when you are trying to creating this user?
> 
>     2. Username is not null field, but form the logs you sent, i see that username is coming as null and this is the reason why you are getting this error.
> 
> 
> Along with screenshot can you also send me the update q2r.log file?
> 
> Thanks
> Yogesh

Hi Yogesh

I am not getting option to create new user, Only thing I am getting is update profile. In update profile I am getting the error. Attached the screenshots.
Thanks
Anil
![screen shot 2019-01-17 at 4 25 04 pm](https://user-images.githubusercontent.com/46744177/51313991-e7dc1700-1a74-11e9-99c4-8ce6e2cb0d09.png)
![screen shot 2019-01-17 at 4 27 13 pm](https://user-images.githubusercontent.com/46744177/51313992-e7dc1700-1a74-11e9-99cf-eb051374ebfa.png)

**Comment by yogeshsd** [comment] 2019-01-17 11:21
Hello Anil,

1. Can you send the screenshot of the update profile popup ?

2. Q2r.log file again

3. The user you had logged in, what's the username? Who creates that user? That user is not admin user.

Did you try logging using admin/admin first time?

Thanks
Yogesh

**Comment by anil1750** [comment] 2019-01-17 11:36
> Hello Anil,
> 
>     1. Can you send the screenshot of the update profile popup ?
> 
>     2. Q2r.log file again
> 
>     3. The user you had logged in, what's the username? Who creates that user? That user is not admin user.
> 
> 
> Did you try logging using admin/admin first time?
> 
> Thanks
> Yogesh

Hi Yogesh

I am logging in as admin/admin user only. I have not created any user. Please find the attached screen shot and log file.

Thanks
Anil

![screen shot 2019-01-17 at 5 04 48 pm](https://user-images.githubusercontent.com/46744177/51316277-2cb67c80-1a7a-11e9-9fca-8a91657451dc.png)
[q2r.log](https://github.com/yogeshsd/query2report/files/2768433/q2r.log)

**Comment by yogeshsd** [comment] 2019-01-17 12:14
Hello Anil,

Now I get it.

Can you send me Catalina.out log file also



Thanks
Yogesh

**Comment by anil1750** [comment] 2019-01-17 12:17
> Hello Anil,
> 
> Now I get it.
> 
> Can you send me Catalina.out log file also
> 
> Thanks
> Yogesh

Hi Yogesh

Please find the catalina.out log file.

Thanks

Anil
[catalina.out.zip](https://github.com/yogeshsd/query2report/files/2768567/catalina.out.zip)

**Comment by yogeshsd** [comment] 2019-01-17 12:53
Hello Anil,

I found the issue.

The problem is with username which comes from  cookies.

The tomcat version used by you is 8.0.53 in which cookies values are enclosed with in double quotes and the parsing is failing.

Can you upgrade to tomcat 8.5.12 or above?

That should solve the problem.

Let me know otherwise

Thanks
Yogesh

**Comment by anil1750** [comment] 2019-01-17 14:10
> Hello Anil,
> 
> I found the issue.
> 
> The problem is with username which comes from cookies.
> 
> The tomcat version used by you is 8.0.53 in which cookies values are enclosed with in double quotes and the parsing is failing.
> 
> Can you upgrade to tomcat 8.5.12 or above?
> 
> That should solve the problem.
> 
> Let me know otherwise
> 
> Thanks
> Yogesh

Hi Yogesh

Thank you and is working now. Now how do I get the schema from the postgresql database. I am able to establish a datasource to DB. I am unable to execute a query as I am not getting the schema. Your help is appreciated,

Thanks

Anil
